### PR TITLE
Merging `dev-es6` into `dev-es6-integration`, need to resolve some conflicts.

### PR DESCRIPTION
**Pull request by sdesalas**

### CODE REVIEW

**Comment by sdesalas** [comment]
FYI the camera FX code is now in `webcam_fx.js`

**Comment by sdesalas** [comment]
I've normally resolved this on my local machine using either TortoiseGit or Webstorm, haven't tried the Github Web UI, but from a quick glance its not enough to do a proper merge (because in this case we need to add the changes to `webcam.js` to `webcamfx.js`.. I think.

**Comment by sdesalas** [comment]
Closing. Better that this is resolved locally by merging `dev-es6` into `dev-es6-camera` as this will give a chance to test merge and patch if needed.

**Comment by sdesalas** [comment]
I've merged into my own branch if its any consolation.

**Comment by raabrp** [comment]
If it's not too much, you can roll back my commits on `dev-es6-integration` and merge your own code in. I'll pull `LW4:dev-es6` into `dev-es6-camera`, get the camera working again and try to avoid future merge conflicts, and push to `dev-es6-integration`.

**Comment by sdesalas** [comment]
Thanks dude 👍 , no need to roll back the commits I think. When you got it working again just merge back into the integration branch.

**Comment by raabrp** [comment]
Will do.

**Pull request closed without merging**
